project:
  name: "News Diversity ILP"
  author: "Sue Huynh"
  version: "1.0.0"

data:
  source: "UCI Online News Popularity"
  dataset_id: 332
  test_size: 0.2
  random_state: 42
  target_transform: " log_shares"  # log transformation of shares

preprocessing:
  scale_features: true
  scaler_type: "standard" 

model:
  type: "XGBoost"
  params:
    objective: "reg:squarederror"
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42

optimization:
  K: 10  # number of articles to select
  diversity_levels: [0, 1, 2, 3, 4, 5, 6, 7]  # for Pareto analysis
  solver: "PULP_CBC_CMD"
  solver_verbose: false

experiments:
  n_seeds: 20  # robustness analysis across random seeds
  seeds: [0, 1, 7, 10, 34, 42, 123, 289, 340, 456, 789, 1001, 1010, 1234, 2026, 3443, 4567, 7890, 8910, 101010]
paths:
  # Base directories
  data_raw: "data/raw"
  data_processed: "data/processed"
  results: "results"
  
  # Results subdirectories
  seed_runs: "results/seed_runs"
  aggregated: "results/aggregated"
  figures: "results/figures"
  tables: "results/tables"
  logs: "results/logs"
  
  # Models
  models: "models/saved"

# Feature selection (optional - document what you used)
features:
  content: [" n_unique_tokens", " num_hrefs", " num_imgs", " num_videos", 
              ' average_token_length',' num_keywords', 
              ' kw_avg_min', ' kw_avg_max',' kw_avg_avg', 
              ' self_reference_avg_sharess',
              ' LDA_00', ' LDA_01', ' LDA_02',
              ' LDA_03', ' LDA_04', 
              ' global_subjectivity',' global_sentiment_polarity', 
              ' global_rate_positive_words',
              ' avg_positive_polarity',
              ' title_subjectivity', ' title_sentiment_polarity']
  temporal: [" weekday_is_monday", " weekday_is_tuesday", " weekday_is_wednesday", "weekday_is_thursday", " weekday_is_friday", " weekday_is_saturday", " weekday_is_sunday" ]
  category: ["d ata_channel_is_lifestyle", " data_channel_is_entertainment", 
             " data_channel_is_bus", " data_channel_is_socmed", 
             " data_channel_is_tech", " data_channel_is_world",
             " data_channel_is_other"]